config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "products#index"

  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end

  resources :products do
    member do
      post :add_to_cart
    end
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  resources :cart_items

  resources :orders do
    member do
      post :pay_with_wechat
      post :pay_with_alipay
      post :apply_to_cancel
    end
  end

  namespace :account do
    resources :orders
  end




end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader

  validates :title, presence: true
  
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_required
  layout "admin"

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      flash[:notice] = "Product Upload"
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      flash[:notice] = "Product Updated"
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:alert] = "Product Removed"
    redirect_to admin_products_path
  end




  private

  def product_params
    params.require(:product).permit(:title, :description, :quantity, :price, :image)
  end



end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
    @product = Product.find(params[:id])
    if !current_cart.products.include?(@product)
      current_cart.add_product_to_cart(@product)
      flash[:notice] = "Added #{@product.title}to cart"
    else
      flash[:warning] = "Already ordered"
    end

      redirect_to :back
  end


end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/edit.html.erb
<h1> Edit Product </h1>

<%= simple_form_for [:admin, @product] do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :quantity %>
<%= f.input :price %>

 <% if @product.image.present? %>
   <span> Current product picture <br>
   <%= image_tag(@product.image.thumb.url) %>
  </span>
 <% end %>

   <%= f.input :image, as: :file %>


<%= f.submit "Edit", class: "btn btn-success" %>

<% end %>

app/views/admin/products/index.html.erb
<h1> Product List </h1>

<div class="pull-right">
  <%= link_to("Add New Product", new_admin_product_path, class: "btn btn-primary") %>
</div>
<br><br><br>

<table class="table table-bordered">
  <thead>
      <tr>
          <th> #</th>
          <th> Product Pic</th>
          <th> Name</th>
          <th> Price</th>
          <th> Option</th>
      </tr>
  </thead>
  <tbody>

    <% @products.each do |product| %>
      <tr>
          <td> <%= product.id %></td>
          <td>
            <!-- wrap whole pic -->
              <%= link_to product_path(product) do %>
                <% if product.image.present? %>
                  <%= image_tag(product.image.thumb.url, class: "thumbnail") %>
                <% else %>
                  <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
                <% end %>
              <% end %>
            <!-- wrap whole pic end -->
          </td>
          <td> <%= product.title %></td>
          <td> <%= product.price %></td>
          <td>
              <%= link_to("Edit", edit_admin_product_path(product), class: "btn btn-sm btn-success") %>
              <%= link_to("Delete", admin_product_path(product), method: :delete, :data => { confirm: "Are you sure?"}, class: "btn btn-sm btn-danger" )%>
          </td>
      </tr>
      <% end %>
  </tbody>

</table>

app/views/admin/products/new.html.erb
<h1> New Product </h1>

<%= simple_form_for [:admin, @product] do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :quantity %>
<%= f.input :price %>
<%= f.input :image, as: :file %>

<%= f.submit "Create Product", class: "btn btn-success" %>

<% end %>

app/views/admin/products/show.html.erb
<h1> <%= @product.title %></h1>